### ISSUE TITLE
Filler items are slightly misaligned

### ISSUE THREAD

**Issue by apresern** [DrewDahlman/Mason#46] opened 2015-04-05 13:12 UTC
Firstly, awesome work with Mason, it's exactly what I've been looking for.

I've got a relatively large page of items, using a few different sizes and it needs to be fluid. One issue I'm having is that when I don't include a gutter, some of the filler items appear misaligned, either causing small gaps between them, or overlapping one another. It's slight, but noticeable.

It looks like some of the filler item properties are calculated as fractions (e.g. left: 810.68px) so I'm not sure if this has anything to do with it. Any ideas? Thanks!

![mason-filler-alignment](https://cloud.githubusercontent.com/assets/1932041/6996923/c4505282-dbc2-11e4-9841-5b085102c825.png)

**Comment by DrewDahlman** [comment] 2015-04-05 15:36
Hmm. Do you happen to have a fiddle?

I think I know exactly what the issue is - depending on browser there are pixel rounding issues and I am doing my best to get them to round correctly, I did recently change the way this is being done so I bet that's an effect of that.

With that said, what happens if you make a 1px gutter are they more aligned? If so then it's a pixel rounding and I can take a look at how things are being handled to ensure a better layout.

**Comment by apresern** [comment] 2015-04-05 17:59
It is a large grid with a lot of items. It's difficult to recreate exactly as items are being generated from a JS object, placed into a template and then shuffled so they appear in a random order (although I don't think that would have an effect?)

http://jsfiddle.net/phkom7d2/

That's with 20 items and you can start to see gaps appearing as you scroll down. They seem to become more pronounced towards the end of the grid when there's even more items.

**Comment by DrewDahlman** [comment] 2015-04-06 15:19
Perfect! thanks for posting this.

Yep as I suspected the issue is pixel rounding. I think I have a solve for this and will mess around later today.

**Comment by apresern** [comment] 2015-04-07 16:34
Great, thanks for getting round to it so quickly! Hope you're able to solve this.

**Comment by DrewDahlman** [comment] 2015-04-15 20:47
This should now be resolved in version 2.0.2

**Closed by DrewDahlman** 2015-04-15 20:47 UTC
Labels: bug

**Comment by apresern** [comment] 2015-04-19 07:46
Works perfectly now, thanks!
