### ISSUE TITLE
Fillers off by exactly 8px?

### ISSUE THREAD

**Issue by Deftwun** [DrewDahlman/Mason#65] opened 2016-09-27 20:33 UTC
[I have this up on codepen.](http://codepen.io/Deftwun/pen/rrmgZv) Not sure why but my filler tiles are all off. If I translate the .mason-filler class by 8px exactly, everything lines up. Seems to still be responsive though so I'll take it. Just seems like maybe a bug or old build? (or more likely I'm missing something)

**Comment by DrewDahlman** [comment] 2016-09-27 20:49
hey @Deftwun - that is interesting. Seems that the body not having a reset on the margin is causing the issue.

by adding:
<pre>
* {
 margin: 0;
}
</pre>

the issue is fixed. SO this is a bug and an easily fixed one, but also a small use case as there is usually a normalizer in place for CSS.

**Comment by Deftwun** [comment] 2016-09-27 21:12
Ah good point. Forgot I didn't have bootstrap included. Thanks!

**Closed** 2016-12-22 05:11 UTC
Labels: bug
