### ISSUE TITLE
Best way to append new content for infinity scrolling page

### ISSUE THREAD

**Issue by Jamie452** [DrewDahlman/Mason#42] opened 2015-01-06 13:16 UTC
I was just wondering if anyone has looked at Mason for an infinity scrolling style page.

Is there a recommended way to append content to the main content div without causing everything to redraw?

Thanks,

Jamie

**Comment by pr1ntr** [comment] 2015-01-10 01:07
bump

**Comment by UnaOmnia** [comment] 2015-01-19 08:38
Yes, knowing how to do so would be excellent!

**Comment by DrewDahlman** [comment] 2015-01-22 05:59
A potential solution for this has been found - @Jamie452 and I are working to see if it is viable and works as it should.

**Comment by UnaOmnia** [comment] 2015-01-22 21:57
What is branch 2 currently solving? I am not sure I follow.. 

Is it that I am swapping out your JS and leaving my mockup the same? Or did anything of the expected setup change?

**Comment by DrewDahlman** [comment] 2015-01-22 22:08
Everything should be the same - the promoted posts did change a little. check the readme as well as the examples in the public folder. you will see a double grid example for how you could potentially setup the infinite scroll.

**Comment by UnaOmnia** [comment] 2015-01-22 22:19
Ok I will check.. sounds great.. I will take it REALLY SLOW and report back
what I got.. I am just working on a simple wordpress loop..



*Ted*

312-292-6931

ted@unaomnia.com

unaomnia.com

**Comment by Jamie452** [comment] 2015-01-22 23:58
@UnaOmnia - just want to point out that the change to promoted posts in the options isn't too obvious, it took me a while to notice that the order of the class_name, x, y has changed from:

```
promoted: [
        [2, 1, 'class_name'],
        [2, 3, 'class_name'],
        [3, 3, 'class_name'],
    ]
```

to:

```
promoted: [
        ['class_name', 2, 1],
        ['class_name', 2, 3],
        ['class_name', 3, 3],
    ]
```

Hopefully that will save you some time :)

**Comment by UnaOmnia** [comment] 2015-01-23 04:42
Yeah I got that. I am going to finalize my lazy load design and get back to
you guys.

I might also want to point out a few things.. if we have the Mason perfect
no gap layout AND NOW we have lazy load, we still are missing a few
elements..

Text resize, truncation, and columnization, as well as image size etc.

I decided that it would be best to break up sections within the Mason grid
into images and excerpts. To solve the image resize issue, I used Binary
Moon (TimThumb guy) new suggestion of not using TImThumb and using
background images. I find this to be a working solution for images inside
the Mason grid, to have an appropriate size.

I am still working on the truncation of text. For example, promoted boxes
could be bigger and therefore have more space for text, i.e. creating yet
another gap if we code an excerpt to be a given length. So I will also be
looking for a way to increase or reduce text, as well as form text into
single and multiple columns, depending on the size of the box, promoted or
otherwise.

All together, this would create a system to RANDOMIZE THE APPEARANCE OF
POSTS IN A LOOP <-- something that has yet to be solved, at least not in a
PERFECTLY JUSTIFIED AND RESPONSIVE way.

Again, I will get back to you all with notes on my discoveries in these
areas.



*Ted*

312-292-6931

ted@unaomnia.com

unaomnia.com

**Comment by UnaOmnia** [comment] 2015-01-24 06:34
I found the issue with my problem. The infinite scroll demo should work, however for the HTML markup you need to be sure you include a class on the grid container to include the necessary CSS to not get the infamous Cannot set property of "0".

.mason-container {
width: 100%;
position: relative;
}

Then be sure this class is on all grids. Then the Mason.js should work just fine. .mason() can be called on different selectors, and the .box and .fillerBox and .custom_filler class can stay the same. 

Fillers remain the same, unless you remove or reorder them. That is what I do. I lazy load and them remove the fillerBox's that get cloned and turned into .custom_fillers. Then I append() the remaining fillerBox's to the next grids filler box container (#fillers). But it is also prudent to make a class .fillers, that essentially does the same thing as #fillers, picks up the display: none CSS, but for all fillerBox containers.. just like my idea for the .mason-container class.

In the infinite scroll demo of mason 2.0 (double_grids), it shows JS specifying the next load. If you were using WordPress you could emulate this better in combination with WordPress pagination and .load() AJAX. 

https://github.com/DrewDahlman/Mason/blob/2.0/public/double_grids.html

http://www.problogdesign.com/wordpress/load-next-wordpress-posts-with-ajax/

But you would need to go further.. MUCH FURTHER.. to remove/append fillers.. and control the size of the elements INSIDE the boxes!!!!

i.e. you have to go further into increasing and decreasing text excerpts, or changing image size based on parent box container etc. 

localnationalnews.com <-- my work so far.. only works up to load 6.. sometimes 11.. not sure why.. it works over and over, but eventually it fails. with no error. I am not sure the cause, so it could have to do with pagination, however I checked for the last page (turned out to be page 14 in my case) and my lazy load did not work up to the last page. I will try to fix that tonight. 

I hope this project turns into something a tiny bit more useful, as randomly sized boxes you can't do anything with, aren't that useful, in and of themselves.

**Comment by DrewDahlman** [comment] 2015-01-28 18:03
I am closing this and going to note that there is an example of adding grids now in the master branch in public/double_grids.html

**Closed by DrewDahlman** 2015-01-28 18:03 UTC
